[webservers]
web-1 ansible_host=89.169.157.80 fqdn=fhm6e5q0l8bm1ao7agel.auto.internal
web-2 ansible_host=93.77.177.150 fqdn=fhm3f5tc31k4t97vu20n.auto.internal

[databases]
main ansible_host=51.250.3.132 fqdn=fhmq5f67f03ntji4u6hg.auto.internal
replica ansible_host=93.77.177.70 fqdn=fhmebijli33sn7apts2h.auto.internal

[storage]
storage ansible_host=93.77.179.24 fqdn=fhm56um56imikdktvg87.auto.internal