apiVersion: 1

contactPoints:
  - orgId: 1
    name: telegram-homework
    receivers:
      - uid: telegram_homework
        type: telegram
        disableResolveMessage: false
        settings:
          chatid: $TELEGRAM_CHAT_ID
          bottoken: $TELEGRAM_BOT_TOKEN
          uploadImage: false